version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-19-feb-2022/motion-backend-assignment/team2:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - ./env/dev.env
    command: "python manage.py runserver 0:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - ./env/dev.env
    ports:
      - 5555:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db:

